### ISSUE TITLE
Replace dependabot message to request adding a comment with JIRA

### ISSUE THREAD

**Issue by xstefank** [wildfly/wildfly-github-bot#161]
Most people can't edit dependabot PRs. So they should just add a new comment with the JIRA.

**Comment by The-Huginn** [comment]
Should we expect a first comment to contain a JIRA?
Also comment message added by the bot should be slightly modified in such case I expect, to not edit the title&description but rather add a new comment

**Comment by xstefank** [comment]
yes, only add new comment

**Comment by xstefank** [comment]
yep, I like the idea that we would need a comment from anyone, mentioning WFLY issue regext match as we do in the description. See what I did for instance in the https://github.com/wildfly/wildfly-github-bot

**Comment by The-Huginn** [comment]
I think this is resolved by 685daa5 and can be closed @xstefank
