### ISSUE TITLE
Don't update the PR description unless there's something to say

### ISSUE THREAD

**Issue by bstansberry** [wildfly/wildfly-github-bot#198]
There are lots of PRs like this where the bot has updated the PR description for no purpose other than to tell the reader they can read more information about the bot.

https://github.com/wildfly/wildfly/pull/17780

Actually even if the bot has done something, writing this doesn't add much value:

More information about the [wildfly-bot[bot]](https://github.com/wildfly/wildfly-github-bot)

The README in that repo is not useful info for somebody reading a PR who clicks on the link. It's all about running the bot, etc, not about what it does.

**Comment by xjusko** [comment]
Hi @bstansberry , is this issue open to work on?

**Comment by bstansberry** [comment]
@The-Huginn Thanks for the update. Sorry; this report wasn't super clear; my main concern was adding the footer when there was nothing else written. I think having the footer when something was written is fine.

**Comment by The-Huginn** [comment]
No worries. I checked the PR and it is removing the footer all together at all scenarios. I requested changes as I suspected that is not expected. Thanks for clarifying.
